POST http://localhost:8080/batch/start
Content-Type: application/json

{
  "id": "id3",
  "jobName": "helloWorldJob"
}

###

POST http://localhost:8080/batch/stop
Content-Type: application/json

{
  "id": "id3",
  "jobName": "helloWorldJob"
}

###

POST http://localhost:8080/batch/restart
Content-Type: application/json

{
  "id": "id3",
  "jobName": "helloWorldJob"
}